name: goat_market
description: "A simple marketplace for goats."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  http: ^1.3.0
  http_parser: ^4.1.2
  image: ^4.5.4
  mime: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.1.0
  location: ^8.0.0
  geocoding: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # Path to your app icon image (1024x1024 recommended)
  adaptive_icon_background: "#ffffff" # Background color for the round icon (can also be a path to an image)
  adaptive_icon_foreground: "assets/icon/app_icon.png" # Path to your icon image
  remove_alpha_ios: true # Removes alpha from the iOS icon

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/app_icon.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/goat_icon.svg