// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqU1qtLiRf8X0Vx39upaa7_5kBD5zLs-8',
    appId: '1:863505535509:web:e1d054baa112260021341c',
    messagingSenderId: '863505535509',
    projectId: 'a04marketplace',
    authDomain: 'a04marketplace.firebaseapp.com',
    storageBucket: 'a04marketplace.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqBFOY7TVKniEJvZYhvrvWpO6tmjU3XF4',
    appId: '1:863505535509:android:ae201bd28d5c869b21341c',
    messagingSenderId: '863505535509',
    projectId: 'a04marketplace',
    storageBucket: 'a04marketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxz_QrcT3Mpw8qqoUTwda9xbKpEI17TH4',
    appId: '1:863505535509:ios:90c70a1d81ca033521341c',
    messagingSenderId: '863505535509',
    projectId: 'a04marketplace',
    storageBucket: 'a04marketplace.firebasestorage.app',
    iosBundleId: 'com.example.a04Marketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxz_QrcT3Mpw8qqoUTwda9xbKpEI17TH4',
    appId: '1:863505535509:ios:90c70a1d81ca033521341c',
    messagingSenderId: '863505535509',
    projectId: 'a04marketplace',
    storageBucket: 'a04marketplace.firebasestorage.app',
    iosBundleId: 'com.example.a04Marketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqU1qtLiRf8X0Vx39upaa7_5kBD5zLs-8',
    appId: '1:863505535509:web:2bb385aaeece360921341c',
    messagingSenderId: '863505535509',
    projectId: 'a04marketplace',
    authDomain: 'a04marketplace.firebaseapp.com',
    storageBucket: 'a04marketplace.firebasestorage.app',
  );

}